<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <DefineConstants>$(DefineConstants);ENABLE_LOOKUP_CREATE</DefineConstants>
    <IsRoslynComponent>true</IsRoslynComponent>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" />
    <PackageReference Include="SortSharp" PrivateAssets="all" />
    <PackageReference Include="System.Text.Json" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="../FluentIcons.Common/Icon.cs" />
    <Compile Include="../FluentIcons.Common/Internals/NonResizableAttribute.cs" />
    <Compile Include="../FluentIcons.Common.Extensions/Collections/BitSetView.cs" />
    <Compile Include="../FluentIcons.Common.Extensions/Collections/SortedLookup.cs" />
  </ItemGroup>

</Project>
