using System.Linq;
using FluentIcons.Common.Internals;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using F = Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace FluentIcons.Common.SourceGeneration;

[Generator]
public sealed class SymbolGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var declarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                (node, _) => node is EnumDeclarationSyntax declaration && declaration.Identifier.Text == "Icon",
                (ctx, _) => (EnumDeclarationSyntax)ctx.Node)
            .Collect();

        context.RegisterSourceOutput(
            declarations.Combine(context.CompilationProvider),
            static (ctx, source) =>
            {
                var (enums, compilation) = source;
                foreach (var declaration in enums)
                {
                    var model = compilation.GetSemanticModel(declaration.SyntaxTree);
                    if (model.GetDeclaredSymbol(declaration) is not INamedTypeSymbol symbol)
                        continue;

                    var ns = symbol.ContainingNamespace.ToDisplayString();
                    var name = symbol.Name;
                    var members = symbol.GetMembers().OfType<IFieldSymbol>()
                        .Where(f => f.HasConstantValue && !f.GetAttributes().Any(a => a.AttributeClass?.Name == nameof(NonResizableAttribute)));

                    var root = F.CompilationUnit()
                        .WithMembers([F.FileScopedNamespaceDeclaration(F.ParseName(ns))
                            .WithMembers([F.EnumDeclaration("Symbol")
                                .WithModifiers([F.Token(SyntaxKind.PublicKeyword)])
                                .WithBaseList(F.BaseList([F.SimpleBaseType(F.ParseTypeName("int"))]))
                                .WithMembers([.. members.Select(m => F.EnumMemberDeclaration(m.Name)
                                    .WithEqualsValue(F.EqualsValueClause(F.ParseExpression($"(int)Icon.{m.Name}"))))])])])
                        .WithLeadingTrivia(F.ParseLeadingTrivia("// <auto-generated/>"))
                        .NormalizeWhitespace();

                    ctx.AddSource($"Symbol.g.cs", root.ToFullString());
                }
            });
    }
}
