<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net45;netstandard2.0;netstandard2.1;net6.0</TargetFrameworks>
    <Description>A shared library for FluentUI System Icons control library.</Description>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
  </PropertyGroup>

  <Choose>
    <When Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'netstandard2.0'))">
      <ItemGroup>
        <PackageReference Include="System.Collections.Immutable" VersionOverride="5.0.0" />
      </ItemGroup>
    </When>
    <When Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'netcoreapp1.0'))">
      <ItemGroup>
        <PackageReference Include="System.Collections.Immutable" />
      </ItemGroup>
    </When>
  </Choose>

  <ItemGroup>
    <ProjectReference Include="..\FluentIcons.Common.SourceGeneration\FluentIcons.Common.SourceGeneration.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" SkipGetTargetFrameworkProperties="true" UndefineProperties="TargetFramework" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FluentIcons.Common.Extensions" />
    <InternalsVisibleTo Include="FluentIcons.Avalonia" />
    <InternalsVisibleTo Include="FluentIcons.Avalonia.Fluent" />
    <InternalsVisibleTo Include="FluentIcons.Maui" />
    <InternalsVisibleTo Include="FluentIcons.Uwp" />
    <InternalsVisibleTo Include="FluentIcons.WinForms" />
    <InternalsVisibleTo Include="FluentIcons.WinUI" />
    <InternalsVisibleTo Include="FluentIcons.Wpf" />
  </ItemGroup>

</Project>
