on:
  workflow_dispatch:
  repository_dispatch:
    types: [deploy]

name: Deploy

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: windows-latest
    steps:
      - name: Setup environments
        id: vars
        run: |
          git config --global core.symlinks true
          git config --global core.autocrlf false
          echo "dotnet_workload_version=$(dotnet workload --version)" >> $env:GITHUB_OUTPUT
          echo "program_data=$env:ProgramData" >> $env:GITHUB_OUTPUT
      - uses: olegtarasov/get-tag@v2-release
        id: tag_name
      - name: Cache .NET workloads
        uses: actions/cache/restore@v4
        with:
          key: dotnet-${{ runner.os }}-${{ runner.arch }}-workloads-${{ steps.vars.outputs.dotnet_workload_version }}
          path: ${{ steps.vars.outputs.program_data }}\dotnet\workloads
      - name: Setup .NET workloads
        run: |
          dotnet workload install wasm-tools-net8
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Cache NuGet packages
        uses: actions/cache/restore@v4
        with:
          key: dotnet-${{ runner.os }}-${{ runner.arch }}-nuget-${{ hashFiles('**/Directory.Packages.props') }}
          path: ~/.nuget/packages
      - name: Build
        run: |
          $env:VERSION_SUFFIX = "${{ steps.tag_name.outputs.tag }}" -replace "^[^\-]+-?", ""
          dotnet publish ./FluentIcons.Gallery/FluentIcons.Gallery.csproj -f net8.0-browser
      - name: Deploy to GitHub Pages
        if: ${{ !contains(steps.tag_name.outputs.tag, '-') }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./FluentIcons.Gallery/bin/Release/net8.0-browser/browser-wasm/AppBundle
          publish_branch: gh-pages
